### ISSUE TITLE
Link outdated

### ISSUE THREAD

**Issue by Gombiembe** [fusion-dancing-eu/fusion-dancing-eu.github.io#1]
The link to the blog post (http://thedancingroot.com/when-fusion-became-fusion-historical-narrative-pt-2/) seems not to function any more. I only see a blank page.

**Comment by LGro** [comment]
Thanks for reporting @Gombiembe. Initially I was hoping that the site would come back, but that doesn't seem to be the case.
I now replaced the link with one to the internet archive's version of the blog post, which is unfortunately not complete but should be an improvement over a broken link.
If you know about an appropriate alternative reference that we could link, let me know.
