### ISSUE TITLE
Add Cider House to events calendar

### ISSUE THREAD

**Issue by KaleidoscopeFusion** [fusion-dancing-eu/fusion-dancing-eu.github.io#12]
Hi,

Can Cider House 2023 be added to the fusion calendar? It's a blues and fusion event in Bristol, UK, 1st-3rd December 2023.

https://www.facebook.com/events/712781990654440

Thank you!

**Comment by LGro** [comment]
Done :relaxed: Even though "Cider House Blues 2023" doesn't scream fusion dancing nearly as loud as almost all of the other events in the calendar. With the transition of the fusion calendar from the ice bear website to fusion-dancing.eu we lost the rule of at least 50% fusion required for events to be listed. You know events across the full spectrum, what do you think would make sense moving forward?

**Comment by KaleidoscopeFusion** [comment]
Thank you! Yes, I do wonder if we need to tweak the name, but Cider House has always been 30% fusion. 
   
  
    
   
  
   I hear you on the 50% rule, I'd probably want more info from organisers where they drop below that in your shoes. For example, the UK didn't have any pure fusion weekends until I started Kaleidoscope so most of UK fusion dancers will come to Cider House as it has a fusion-heavy crowd and we put care into the fusion aspects - including having a dedicated fusion room some nights. 
   
  
    
   
  
   If you'd rather drop Cider House for not having that 50%+ then I respect that! I don't think I knew the previous site and rules.
   
  
    
   
  
   Thanks 
   
  
   Siân 
   
   
   
    On 06/08/2023 08:55 BST Lukas Großberger ***@***.***> wrote:
    
   
     
    
   
     
    
     
   Done ☺️ Even though "Cider House Blues 2023" doesn't scream fusion dancing nearly as loud as almost all of the other events in the calendar. With the transition of the fusion calendar from the ice bear website to fusion-dancing.eu we lost the rule of at least 50% fusion required for events to be listed. You know events across the full spectrum, what do you think would make sense moving forward?

**Comment by KaleidoscopeFusion** [comment]
Sorry, realise I wasn't quite accurate. There is MMFX but that's micro, and Lowland Fusion Retreat, but that's a residential and a very different style of event, so I think the point stands!
   
   
   
    On 06/08/2023 10:20 BST Siân Kathryn ***@***.***> wrote:
    
   
     
    
   
     
    
   
    Thank you! Yes, I do wonder if we need to tweak the name, but Cider House has always been 30% fusion. 
    
   
     
    
   
    I hear you on the 50% rule, I'd probably want more info from organisers where they drop below that in your shoes. For example, the UK didn't have any pure fusion weekends until I started Kaleidoscope so most of UK fusion dancers will come to Cider House as it has a fusion-heavy crowd and we put care into the fusion aspects - including having a dedicated fusion room some nights. 
    
   
     
    
   
    If you'd rather drop Cider House for not having that 50%+ then I respect that! I don't think I knew the previous site and rules.
    
   
     
    
   
    Thanks 
    
   
    Siân 
    
    
    
     On 06/08/2023 08:55 BST Lukas Großberger ***@***.***> wrote:
     
    
      
     
    
      
     
      
    Done ☺️ Even though "Cider House Blues 2023" doesn't scream fusion dancing nearly as loud as almost all of the other events in the calendar. With the transition of the fusion calendar from the ice bear website to fusion-dancing.eu we lost the rule of at least 50% fusion required for events to be listed. You know events across the full spectrum, what do you think would make sense moving forward?

**Comment by LGro** [comment]
Given that the "pure" fusion events aren't drowning in a mass of hybrid ones I see no harm done in having e.g. more Blues focused ones. After all the calendar is intended as a tool for folks to find fusion events, and then a wider spectrum means folks need to look in fewer different places to find suitable events. Thanks for sharing your thoughts on this :relaxed:
